export interface HealthData {
    'pct_cah_hospitals_cehrt'?: string,
    'pct_critical_access_hospitals_basic_ehr_no_notes'?: string,
    'pct_critical_access_hospitals_basic_ehr_notes'?: string,
    'pct_hospitals_basic_ehr_no_notes'?: string,
    'pct_hospitals_basic_ehr_notes'?: string,
    'pct_hospitals_cehrt'?: string,
    'pct_hospitals_find_clinical_info': string,
    'pct_hospitals_integrate_any_clinical_info': string,
    'pct_hospitals_integrate_scr': string,
    'pct_hospitals_patients_ecopy_discharge_instr': string,
    'pct_hospitals_patients_ecopy_ehr': string,
    'pct_hospitals_patients_secure_message': string,
    'pct_hospitals_patients_vdt': string,
    'pct_hospitals_receive_clinical_info': string,
    'pct_hospitals_send_clinical_info': string,
    'pct_hospitals_share_care_summaries_any_outside_ambu_provs': string,
    'pct_hospitals_share_care_summaries_any_outside_hospitals': string,
    'pct_hospitals_share_care_summaries_any_outside_provs': string,
    'pct_hospitals_share_labs_any_outside_ambu_provs': string,
    'pct_hospitals_share_labs_any_outside_hospitals': string,
    'pct_hospitals_share_labs_any_outside_provs': string,
    'pct_rural_hospitals_basic_ehr_no_notes': string,
    'pct_rural_hospitals_basic_ehr_notes': string,
    'pct_small_hospitals_basic_ehr_no_notes': string,
    'pct_small_hospitals_basic_ehr_notes': string,
    'pct_small_rural_hospitals_cehrt': string,
    'period': string,
    'region': string,
    'region_code': string,
}

export interface Chart {
    'title': string,
    'type': string,
    'data': Array<any>,
    'options'?: any,
    'columnNames'?: Array<any>,
    'height': number,
    'width': number,
}